name: chem_tools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rdkit=2023.03.1
  - pandas=2.0.1
  - numpy=1.24.3
  - streamlit=1.22.0
  - matplotlib=3.7.1
  - pillow=9.5.0
  - pip=23.0.1
